### ISSUE TITLE
大佬！能不能指点下该如何修改内置的节目源和epg，父母在家不太会扫码推送节目源，

### ISSUE THREAD

**Issue by xiaomageaaa** [yaoxieyoulei/my_tv#12]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
自己编译的话 改[这个文件](https://github.com/yaoxieyoulei/my_tv/blob/main/lib/common/values/constants.dart)
扫码推送 只能改节目源，不能改epg

**Comment by xiaomageaaa** [comment]
谢谢！
