### ISSUE TITLE
添加频道收藏功能

### ISSUE THREAD

**Issue by Goforfreedom** [yaoxieyoulei/my_tv#13]
### 功能描述
请提供对所请求功能的清晰描述。
频道收藏

### 目标
请描述你希望通过这个功能实现的目标。
通过频道收藏，方便找到自己喜爱的频道，可以通过在频道界面长按频道名弹出收藏按钮。
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
请移步我的另一个项目 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.3.0
