### ISSUE TITLE
增加视频信息的功能需求

### ISSUE THREAD

**Issue by Exlany** [yaoxieyoulei/my_tv#14]
### 功能描述
希望在节目页分辨率信息后面还能显示编码格式、码率、动态范围等信息

### 目标
方便查看不同源的质量

### 其他
如APTV能展示视频信息、音频信息

最后非常感谢作者的付出，几个开源的TV类APP我都安装了给父母用，最后反馈这个是最稳定的，希望作者能留下捐赠二维码。

**Comment by yaoxieyoulei** [comment]
请移步我的另一个项目 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.3.0
目前视频信息不太完善
