### ISSUE TITLE
很多频道没声音，同样的源在TVBox里播放正常

### ISSUE THREAD

**Issue by 4yt1k** [yaoxieyoulei/my_tv#15]
我是安装在小米电视里面的，配置了自定义的源。

另外就是在老机顶盒会闪退，无法正常启动。
这个盒子只能安装原版的TVBox，系统是什么版本不大清楚。

**Comment by yaoxieyoulei** [comment]
没声音可能是编码格式不支持，软件现在不支持软解。闪退估计android版本是4.4

**Comment by 4yt1k** [comment]
> 没声音可能是编码格式不支持，软件现在不支持软解。闪退估计android版本是4.4

有点遗憾，我最想装在机顶盒里给老人用，我查了，盒子的系统确实是安卓4.4。
现在开机就进入电视直播的软件好用的不多，现在装了my-tv1.8.6，这个最流畅，可惜没有368频道。
另外装了小薇直播、小酷直播，这两个会卡，而且刚启动的时候都是强行进入广告频道，老人脑子不太好合了，多操作几步她都觉得复杂，搞不定。

我自己整理了一些源，在小米电视里面配合最新版的tvbox比较好用，但小米电视不让设置开机启动软件。
机顶盒只能装以前比较老的原版tvbox，很多功能没用，不能设置开机启动，也不能设置启动直接进入电视直播。

我最想要的是基于my-tv1.8.6这样相对比较稳定可用又能自定义源的直播软件。
目前作者你开发的这个不能在安卓4.4上安装，在小米电视里装上配置好了，却没有声音。。。

**Comment by HTWMedia** [comment]
我在作者的基础上做了个app，支持Android4.4及IPv4，楼主可以试下：[HTV](https://github.com/HTWMedia/HTV)
